### PR TITLE
Added lz4 support

### PR DESCRIPTION
**Pull request by jtsylve**
This PR adds support for LZ4 compression.  There's an added dependency on liblz4.

### CODE REVIEW

**Comment by scudette** [comment]
Can you please update the README.linux, README.windows and especially the dockerfile to make sure the new dependency gets installed?

**Comment by jtsylve** [comment]
I'd have to set up a Linux VM to figure out the exact steps for that, and I don't have those extra cycles at the moment. (We use a cmake setup to vendor, build, and cross-compile all the dependencies on macOS).

**Comment by scudette** [comment]
I tried to build it quickly (I assume this is the source https://github.com/lz4/lz4) but it seems that their build system is very primitive - they are not really using autoconf so cross compiling is going to be hard.

Since we have to cross compile (for windows support) and also have to be able to build statically we really need to have this integrated better. 

One way is to copy their source into the third party library and just link to it statically in our build system. It does not look too complicated to do that (their code seem pretty standalone).

Another way is to add optional support via #ifdef tags so it builds without the library installed.

Sorry that c++ dependency management sucks so bad :-(.

**Comment by jtsylve** [comment]
I'm cross-compiling that as well.  

```
CC=x86_64-w64-mingw32-gcc AR=x86_64-w64-mingw32-ar DESTDIR=<full path to install prefix> make -C lib install
```

If you want to prevent it from building a shared library too, you need to change line 45 `of lib/Makefile`

**Comment by scudette** [comment]
Ok let me play with it - I think I can get the docker files fixed up. If you are happy I can do this in the next PR

**Pull request merged**
